set -g default-terminal "xterm-kitty"
unbind r
bind r source-file ~/.tmux.conf
bind-key y new-window -c "#{pane_current_path}"
set -g mouse on

set-option -g status-position top
# List of plugins
set -g @plugin 'tmux-plugins/tpm'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
