vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("nnoremap <C-e> :Explore<CR>")
vim.cmd("nnoremap <C-h> :bp<CR>")
vim.cmd("nnoremap <C-l> :bn<CR>")
vim.cmd("set autochdir")
vim.cmd("inoremap ( ()<Left>")
vim.cmd("inoremap [ []<Left>")
vim.cmd("inoremap { {}<Left>")
vim.cmd("inoremap \" \"\"<Left>")
vim.cmd("set number")
vim.cmd("map <leader><space> :let @/=''<cr>") -- leader key at this point is '\' but would change to space later during lazy setup
vim.cmd("set noshowmode")
